# Generated by Django 5.1.6 on 2025-03-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='plane_model',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='plane',
            name='plane_type',
            field=models.CharField(max_length=15),
        ),
    ]
