# Generated by Django 5.1.6 on 2025-03-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0002_alter_plane_plane_model_alter_plane_plane_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='plane_model',
            field=models.CharField(max_length=50),
        ),
    ]
